default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: lojbo_development

test:
  <<: *default
  database: lojbo_test

production:
  <<: *default
  database: lojbo_production
  username: lojbo
  password: <%= ENV['LOJBO_DATABASE_PASSWORD'] %>
