# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b28df2235846dc4eda0e141d0c6be55037457b9dacabd6261bf8dc3b31bfd2c2866dd925e1ea24067645463c5f748b74131a71df4af50cc73f3d43da75764f93

test:
  secret_key_base: 90f7b5f7fdc3aee56eaca8b49b02bbb6cfdcec5658cb5c003dc2742bd1abe7c208c9896d3d651a1e57353009a35163e87abb3ed13fcfa2f63e0bb8373e7459a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
